/**
 * The palette as TypeScript. GENERATED — edit tokens.css instead.
 *
 * React Native style props take colours as values, not class names, so an icon
 * tint or a native option cannot read a CSS variable.
 *
 * Class names remain the way to style anything that takes one. This is only for
 * the props that cannot — and since the palette switches at runtime, read it
 * through the app's `useColors()`, never by picking one of these at import.
 */
export const palettes = {
  light: {
    background: '#f6f2e9',
    foreground: '#1a1612',
    card: '#fcfaf5',
    cardForeground: '#1a1612',
    popover: '#fcfaf5',
    popoverForeground: '#1a1612',
    primary: '#8f5c0f',
    primaryForeground: '#fcfaf5',
    primarySoft: '#f4e7c8',
    secondary: '#ece6d9',
    secondaryForeground: '#4a4237',
    muted: '#efeadf',
    mutedForeground: '#5c5347',
    subtleForeground: '#6f665a',
    accent: '#e6dfd0',
    accentForeground: '#1a1612',
    destructive: '#b83a32',
    destructiveForeground: '#fcfaf5',
    live: '#c4302b',
    success: '#37703f',
    border: '#e4dccb',
    input: '#d3c9b4',
    ring: '#8f5c0f',
    chart1: '#8f5c0f',
    chart2: '#b98a3a',
    chart3: '#7a6f5f',
    chart4: '#c9a15a',
    chart5: '#a89c88',
    sidebar: '#fcfaf5',
    sidebarForeground: '#1a1612',
    sidebarPrimary: '#8f5c0f',
    sidebarPrimaryForeground: '#fcfaf5',
    sidebarAccent: '#e6dfd0',
    sidebarAccentForeground: '#1a1612',
    sidebarBorder: '#e4dccb',
    sidebarRing: '#8f5c0f',
  },
  dark: {
    background: '#0f0d0b',
    foreground: '#f4efe3',
    card: '#1a1612',
    cardForeground: '#f4efe3',
    popover: '#241f1a',
    popoverForeground: '#f4efe3',
    primary: '#e8a33d',
    primaryForeground: '#1a1206',
    primarySoft: '#2f2513',
    secondary: '#2c261f',
    secondaryForeground: '#f4efe3',
    muted: '#2c261f',
    mutedForeground: '#a99d89',
    subtleForeground: '#8a7f70',
    accent: '#372f27',
    accentForeground: '#f4efe3',
    destructive: '#d2554b',
    destructiveForeground: '#f4efe3',
    live: '#e5484d',
    success: '#7dab86',
    border: '#2a241e',
    input: '#3a322a',
    ring: '#e8a33d',
    chart1: '#e8a33d',
    chart2: '#b8ad96',
    chart3: '#8a806f',
    chart4: '#c98a2e',
    chart5: '#6a6054',
    sidebar: '#1a1612',
    sidebarForeground: '#f4efe3',
    sidebarPrimary: '#e8a33d',
    sidebarPrimaryForeground: '#1a1206',
    sidebarAccent: '#372f27',
    sidebarAccentForeground: '#f4efe3',
    sidebarBorder: '#2a241e',
    sidebarRing: '#e8a33d',
  },
} as const;

export type Palette = (typeof palettes)['light' | 'dark'];
export type ColorToken = keyof Palette;
