-- Role permissions as data, not as conditions baked into policies.
--
-- Until now each policy hardcoded its own trust check (`trust in ('reviewer',
-- 'admin')`), so changing what a role may do meant writing a migration, and
-- the rules were scattered across six policies with no single place to read
-- them. This is the same shape np-mono uses: an enum of capabilities, a table
-- mapping role to capability, and one `authorize()` function that every policy
-- defers to.
--
-- The security boundary does not move — it is still enforced in Postgres, and
-- a client still cannot grant itself anything. What changes is that toggling a
-- capability becomes an admin action rather than a deploy.

create type app_permission as enum (
  'segments.propose',      -- create a draft segment
  'segments.publish',      -- make a segment visible in the player
  'segments.review',       -- see and act on other people's drafts
  'segments.delete',       -- remove any segment
  'artists.edit',          -- names, bios, photos
  'users.manage'           -- assign trust levels
);

create table role_permissions (
  id         bigint generated by default as identity primary key,
  role       trust_level not null,
  permission app_permission not null,
  unique (role, permission)
);

alter table role_permissions enable row level security;

-- Readable by anyone signed in, so the admin UI can render the matrix.
-- Writable only through `set_role_permission()` below.
create policy "role permissions are readable"
  on role_permissions for select to authenticated using (true);

grant select on role_permissions to authenticated;

-- Defaults mirror the behaviour that was previously hardcoded.
insert into role_permissions (role, permission) values
  ('contributor', 'segments.propose'),

  -- Trusted publishes its own work without review — the reward for a track
  -- record — but still cannot touch anyone else's.
  ('trusted', 'segments.propose'),
  ('trusted', 'segments.publish'),

  ('reviewer', 'segments.propose'),
  ('reviewer', 'segments.publish'),
  ('reviewer', 'segments.review'),
  ('reviewer', 'segments.delete'),
  ('reviewer', 'artists.edit'),

  ('admin', 'segments.propose'),
  ('admin', 'segments.publish'),
  ('admin', 'segments.review'),
  ('admin', 'segments.delete'),
  ('admin', 'artists.edit'),
  ('admin', 'users.manage');
-- `blocked` deliberately gets no rows: absence of a grant is the block.

create or replace function authorize(requested app_permission)
returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1
    from public.role_permissions rp
    join public.profiles p on p.trust = rp.role
    where p.id = (select auth.uid()) and rp.permission = requested
  );
$$;

grant execute on function authorize(app_permission) to authenticated;

-- Only an admin may change the matrix, and only through this function — the
-- table itself has no INSERT/UPDATE/DELETE grant for `authenticated`.
create or replace function set_role_permission(
  target_role trust_level,
  target_permission app_permission,
  enabled boolean
) returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  if not public.authorize('users.manage') then
    raise exception 'not permitted to change role permissions';
  end if;

  -- An admin removing their own ability to manage users would lock the
  -- instance out of its own permission matrix with no way back in.
  if target_role = 'admin' and target_permission = 'users.manage' then
    raise exception 'admin must retain users.manage';
  end if;

  if enabled then
    insert into public.role_permissions (role, permission)
    values (target_role, target_permission)
    on conflict (role, permission) do nothing;
  else
    delete from public.role_permissions
    where role = target_role and permission = target_permission;
  end if;
end;
$$;

grant execute on function set_role_permission(trust_level, app_permission, boolean) to authenticated;
